services:
  - type: web
    name: digiindia-platform
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: JWT_SECRET
        value: digi-india-881238-17136031-lucky-project-222594960207
      - key: PASSWORD_PEPPER
        value: hGhdbw8FdCjWuqRFlF3EyY5VohMf3Thvof864WMrBKo
      - key: ADMIN_EMAIL
        value: its.akshatnetworkhub23@gmail.com
      - key: ADMIN_PASSWORD
        value: Admin@987
      - key: FIREBASE_PROJECT_ID
        value: digiindia-studentcollaboration
